name: Main workflow

on: [push]

jobs:
    security:
        name: Security
        runs-on: ubuntu-latest
        steps:
            -   name: Check out repository code
                uses: actions/checkout@master

            -   name: Setup PHP
                uses: shivammathur/setup-php@master
                with:
                    php-version: '8.2'

            -   name: Validate composer file
                run: composer validate --no-check-version

            -   name: Dependencies installation
                run: composer install

            -   name: Audit composer dependencies
                run: composer audit

    code-quality:
        name: Code quality
        runs-on: ubuntu-latest
        steps:
            -   name: Check out repository code
                uses: actions/checkout@master

            -   name: Setup PHP
                uses: shivammathur/setup-php@master
                with:
                    php-version: '8.2'

            -   name: Validate composer file
                run: composer validate --no-check-version

            -   name: Dependencies installation
                run: composer install

            -   name: Run code-quality analysis
                run: composer code-quality

    tests:
        name: Tests
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:8
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: false
                    MYSQL_ROOT_PASSWORD: sandbox
                    MYSQL_DATABASE: sandbox_test
                ports:
                    - 3306/tcp
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        steps:
            -   name: Check out repository code
                uses: actions/checkout@master

            -   name: Setup PHP
                uses: shivammathur/setup-php@master
                with:
                    php-version: '8.2'

            -   name: Validate composer file
                run: composer validate --no-check-version

            -   name: Dependencies installation
                run: composer install --no-progress --prefer-dist --optimize-autoloader

            -   name: Setup test env
                run: |
                    mysql -h 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -psymfony -e 'CREATE DATABASE IF NOT EXISTS sandbox_test;'
                    cp .env.test .env.test.local
                    printf '\nDATABASE_URL=mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony\n' >> .env.test.local
                    cat .env.test.local

            -   name: Run Migration
                run: |
                    php bin/console d:s:u -n -e test --force || echo "No migrations found or schema update failed"
                    php bin/console d:m:m -n -e test || echo "No migrations found or migration failed"

            -   name: Run fixtures
                run: php bin/console d:f:l -n -e test

            -   name: Run tests
                run: composer tests
